import { Tool, ToolCategory } from "@/types/onboarding";

export const TOOLS: Tool[] = [
  // CRM
  {
    id: "hubspot",
    name: "HubSpot",
    category: "crm",
    description: "Inbound marketing, sales, and service software.",
    icon: "🟧",
    logo: "/assets/crm-logos/hubspot.svg",
    popular: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: "crm",
    description: "Cloud-based customer relationship management platform.",
    icon: "☁️",
    logo: "/assets/crm-logos/salesforce.svg",
    popular: true,
  },
  {
    id: "leadsquared",
    name: "Leadsquared",
    category: "crm",
    description: "Lead management and marketing automation platform.",
    icon: "📈",
    logo: "/assets/crm-logos/leadsquared.png",
  },
  {
    id: "freshsales",
    name: "Freshsales",
    category: "crm",
    description: "AI-powered CRM with email, phone, and activity tracking.",
    icon: "🍃",
    logo: "/assets/crm-logos/freshsales.svg",
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    category: "crm",
    description: "Global online sales suite to manage sales and contacts.",
    icon: "💼",
    logo: "/assets/crm-logos/zoho_logo_icon_169675.svg",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "crm",
    description: "Sales pipeline and CRM tool for small-to-medium teams.",
    icon: "⚡",
    logo: "/assets/crm-logos/pipedrive.png",
  },
  {
    id: "monday-crm",
    name: "Monday CRM",
    category: "crm",
    description: "Customizable sales CRM to manage pipelines and processes.",
    icon: "📅",
    logo: "/assets/crm-logos/monday-crm.jpeg",
  },
  {
    id: "close-crm",
    name: "Close CRM",
    category: "crm",
    description: "Inside sales CRM designed to double productivity.",
    icon: "🎯",
    logo: "/assets/crm-logos/close-crm.svg",
  },
  {
    id: "limechat",
    name: "LimeChat",
    category: "communication",
    description: "AI-powered WhatsApp CRM and support automation for e-commerce.",
    icon: "💬",
    logo: "/assets/crm-logos/limechat.jpeg",
  },

  // Payments
  {
    id: "razorpay",
    name: "Razorpay",
    category: "payments",
    description: "Popular payment gateway for businesses in India.",
    icon: "💳",
    logo: "/assets/crm-logos/razorpay.svg",
    popular: true,
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Financial infrastructure and payments platform for the internet.",
    icon: "🟪",
    logo: "/assets/crm-logos/stripe.svg",
    popular: true,
  },
  {
    id: "payu",
    name: "PayU",
    category: "payments",
    description: "Local payment processing solutions for emerging markets.",
    icon: "💸",
    logo: "/assets/crm-logos/payu.png",
  },
  {
    id: "cashfree",
    name: "Cashfree",
    category: "payments",
    description: "Bulk payouts, payment gateways, and banking APIs.",
    icon: "🏦",
    logo: "/assets/crm-logos/Cashfree.svg",
  },
  {
    id: "paytm-business",
    name: "Paytm Business",
    category: "payments",
    description: "Merchant payments and business financial operations.",
    icon: "📱",
    logo: "/assets/crm-logos/paytm.svg",
  },

  // E-commerce
  {
    id: "shopify",
    name: "Shopify",
    category: "ecommerce",
    description: "All-in-one commerce platform to start, run, and grow a store.",
    icon: "🛍️",
    logo: "/assets/crm-logos/shopify.svg",
    popular: true,
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "ecommerce",
    description: "Open-source e-commerce plugin built for WordPress.",
    icon: "🛒",
    logo: "/assets/crm-logos/WooCommerce_Logo.svg",
  },
  {
    id: "magento",
    name: "Magento",
    category: "ecommerce",
    description: "Flexible, enterprise-grade e-commerce storefront builder.",
    icon: "🧡",
    logo: "/assets/crm-logos/magento.svg",
  },
  {
    id: "unicommerce",
    name: "Unicommerce",
    category: "ecommerce",
    description: "SaaS-based e-commerce supply chain management technology.",
    icon: "📦",
    logo: "/assets/crm-logos/unicommerce.jpeg",
  },

  // Ads
  {
    id: "meta-ads",
    name: "Meta Ads",
    category: "ads",
    description: "Sync campaign spend, impressions, and leads.",
    icon: "📢",
    logo: "/assets/crm-logos/meta-ads.png",
    popular: true,
  },
  {
    id: "google-ads",
    name: "Google Ads",
    category: "ads",
    description: "Sync campaign performance and conversions.",
    icon: "🔍",
    logo: "/assets/crm-logos/google-ads.png",
    popular: true,
  },

  // Communication
  {
    id: "whatsapp-business",
    name: "WhatsApp Business",
    category: "communication",
    description: "Interact with customers via automated messages and support.",
    icon: "💬",
    logo: "/assets/crm-logos/whatsapp.svg",
    popular: true,
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "communication",
    description: "Customer service platform with live chat, AI, and helpdesk.",
    icon: "💬",
    logo: "/assets/crm-logos/intercom.svg",
    popular: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "communication",
    description: "Web service APIs for sending SMS, calls, and emails.",
    icon: "📞",
    logo: "/assets/crm-logos/twilio.svg",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    category: "communication",
    description: "Omnichannel customer service and ticketing system.",
    icon: "🎧",
    logo: "/assets/crm-logos/freshdesk.svg",
  },

  // Accounting
  {
    id: "tally",
    name: "Tally",
    category: "accounting",
    description: "Sync invoices, ledgers, and financial data.",
    icon: "📊",
    logo: "/assets/crm-logos/tally.svg",
  },
  {
    id: "zoho-books",
    name: "Zoho Books",
    category: "accounting",
    description: "Sync invoices, expenses, and payments.",
    icon: "📓",
    logo: "/assets/crm-logos/zoho-books.png",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "crm", label: "CRM / Sales" },
  { id: "payments", label: "Payments" },
  { id: "ecommerce", label: "E-commerce" },
  { id: "communication", label: "Communication" },
] as const;
